<table>
   <thead>
       <tr>
             <th>Code</th>
              <th>Name</th>
              <th>Vendor</th>
              <th>Category</th>
              <th>SubCategory</th>
              <th>U.O.M</th>
              <th>Price</th>
              <th>Cost Price</th>
              <th>OnHold</th>
              <th>CurrentStock</th>
                <th>unitprice</th>
               <th>original_price</th>
               <th>cost_price</th>
               <th>special_price</th>
               <th>status</th>
               <th>field1</th>
               <th>field2</th>
               <th>field3</th>
               <th>field4</th>
               <th>field5</th>
               <th>field6</th>
               <th>field7</th>
               <th>field8</th>
               <th>field9</th>
               <th>field10</th>
               <th>added_by</th>
               <th>new</th>
               <th>featured</th>
               <th>best_selling</th>
               <th>deal_of_the_day</th>
               <th>deal_date</th>
               <th>purchase_price</th>
               <th>shipping_cost</th>
               <th>unit_price</th>
               <th>on_hold_qty</th>
               <th>volume_box</th>
               <th>ct_box</th>
               <th>weight_box</th>
               <th>warehouse_qty</th>
               <th>product_rating</th>
               <th>rating_value</th>
               <th>nb_boxes_1</th>
               <th>nb_boxes_1_price</th>
               <th>nb_boxes_2</th>
               <th>nb_boxes_2_price</th>
               <th>nb_boxes_3</th>
               <th>nb_boxes_3_price</th>
               <th>size</th>
               <th>location</th>
               <th>class_a_price</th>
               <th>class_b_price</th>
               <th>class_c_price</th>
               <th>item_box</th>
               <th>upc_number</th>
            </tr>
   </thead>
   <tbody>
    <?php $reports = \App\ProductReport\Item::where('report_id','=',$id)->get(); ?>
      @foreach ($reports as $item)
         <tr>
            <td>{{$item->code}}</td>
            <td>{{$item->product_name}}</td> 
            
            <td></td> 
            <td>{{$item->category_name}}</td> 
            <td></td> 
            <td>{{$item->unit}}</td> 
            <td>{{$item->price}}</td> 
            <td>{{$item->sale_price}}</td> 
            <td>{{$item->on_hold_qty}}</td>         
            <td>{{$item->current_stock}}</td> 
            <td>{{$item->unitprice}}</td>  
            <td>{{$item->original_price}}</td>  
            <td>{{$item->sale_price}}</td>  
            <td>{{$item->special_price}}</td>  
            
            <td>{{$item->status}}</td>  
            <td>{{$item->field1}}</td>  
            <td>{{$item->field2}}</td>  
            <td>{{$item->field3}}</td>  
            <td>{{$item->field4}}</td>  
            <td>{{$item->field5}}</td>  
            <td>{{$item->field6}}</td>  
            <td>{{$item->field7}}</td>  
            <td>{{$item->field8}}</td>  
            <td>{{$item->field9}}</td>  
            <td>{{$item->field10}}</td>  
            <td>{{$item->added_by}}</td>  

            <td>{{$item->new}}</td>  
            <td>{{$item->featured}}</td>  
            <td>{{$item->best_selling}}</td>  
            <td>{{$item->deal_of_the_day}}</td>  
            <td>{{$item->deal_date}}</td>  
            <td>{{$item->purchase_price}}</td>  
            <td>{{$item->shipping_cost}}</td>  
            <td>{{$item->unit_price}}</td>  
            <td>{{$item->on_hold_qty}}</td>  
            <td>{{$item->volume_box}}</td>  
            <td>{{$item->ct_box}}</td>  
            <td>{{$item->weight_box}}</td>  
            <td>{{$item->warehouse_qty}}</td>  
            <td>{{$item->product_rating}}</td>  
            <td>{{$item->rating_value}}</td>  
            <td>{{$item->nb_boxes_1}}</td>  
            <td>{{$item->nb_boxes_1_price}}</td>  
            <td>{{$item->nb_boxes_2}}</td>  
            <td>{{$item->nb_boxes_2_price}}</td>  
            <td>{{$item->nb_boxes_3}}</td>  
            <td>{{$item->nb_boxes_3_price}}</td>  
            <td>{{$item->size}}</td>  
            <td>{{$item->location}}</td>  
            <td>{{$item->class_a_price}}</td>  
            <td>{{$item->class_b_price}}</td>  
            <td>{{$item->class_c_price}}</td>  
            <td>{{$item->item_box}}</td>  
            <td>{{$item->upc_number}}</td> 
         </tr>
      @endforeach
   </tbody>
</table>