<?php

namespace App;

// use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Support\Search;

class User extends Authenticatable
{
    // use Notifiable;
    protected $connection = "mysql";
    use Search;

    protected $search = [
        'name', 'title', 'telephone', 'extension', 'mobile_number',
        'email'
    ];

    protected $columns = [
        'id', 'name', 'title', 'telephone', 'extension', 'mobile_number',
        'email',  'created_at',
        'manager_id',
        'is_admin',
        'is_active',
        'is_settings_tab',
        'is_sales_tab',
        'is_procurment_tab',
        'is_accounting_tab',
        'is_company_tab',
        'is_dashboard',
        //settings
        'is_deliverycondition_tab',
        'is_paymentcondition_tab',
        'is_exchangerate_tab',
        'is_uom_tab',
        'is_counters_tab',
        'is_currencies_tab',
        'is_warehouses_tab',
        'is_categories_tab',
        'is_subcategories_tab',
        'is_deliverycondition_create',
        'is_deliverycondition_edit',
        'is_deliverycondition_delete',
        'is_deliverycondition_view',
        'is_paymentcondition_create',
        'is_paymentcondition_edit',
        'is_paymentcondition_delete',
        'is_paymentcondition_view',
        'is_exchangerate_create',
        'is_exchangerate_edit',
        'is_exchangerate_delete',
        'is_exchangerate_view',
        'is_uom_create',
        'is_uom_edit',
        'is_uom_delete',
        'is_uom_view',
        'is_counters_create',
        'is_counters_edit',
        'is_counters_delete',
        'is_counters_view',
        'is_currencies_create',
        'is_currencies_edit',
        'is_currencies_delete',
        'is_currencies_view',
        'is_warehouses_create',
        'is_warehouses_edit',
        'is_warehouses_delete',
        'is_warehouses_view',
        'is_categories_create',
        'is_categories_edit',
        'is_categories_delete',
        'is_categories_view',
        'is_subcategories_create',
        'is_subcategories_edit',
        'is_subcategories_delete',
        'is_subcategories_view',
        //company
        'is_accounts_tab',
        'is_transferaccounts_tab',
        'is_deposit_tab',
        'is_returndeposit_tab',
        'is_employees_tab',
        'is_payroll_tab',
        'is_accounts_create',
        'is_accounts_edit',
        'is_accounts_delete',
        'is_accounts_view',
        'is_transferaccounts_create',
        'is_transferaccounts_edit',
        'is_transferaccounts_delete',
        'is_transferaccounts_view',
        'is_deposit_create',
        'is_deposit_edit',
        'is_deposit_delete',
        'is_deposit_view',
        'is_returndeposit_create',
        'is_returndeposit_edit',
        'is_returndeposit_delete',
        'is_returndeposit_view',
        'is_employees_create',
        'is_employees_edit',
        'is_employees_delete',
        'is_employees_view',
        'is_payroll_create',
        'is_payroll_edit',
        'is_payroll_delete',
        'is_payroll_view',
        //sales
        'is_clients_tab',
        'is_quotations_tab',
        'is_salesorders_tab',
        'is_clients_create',
        'is_clients_edit',
        'is_clients_delete',
        'is_clients_view',
        'is_quotations_create',
        'is_quotations_edit',
        'is_quotations_delete',
        'is_quotations_view',
        'is_salesorders_create',
        'is_salesorders_edit',
        'is_salesorders_delete',
        'is_salesorders_view',
        //Accounting Tab
        'is_advancepayments_tab',
        'is_invoices_tab',
        'is_creditnotes_tab',
        'is_debitnotes_tab',
        'is_clientpayments_tab',
        'is_clientsoa_tab',
        'is_vendorexpenses_tab',
        'is_bills_tab',
        'is_vendorpayments_tab',
        'is_vendorsoa_tab',
        'is_advancepayments_create',
        'is_advancepayments_edit',
        'is_advancepayments_delete',
        'is_advancepayments_view',
        'is_invoices_create',
        'is_invoices_edit',
        'is_invoices_delete',
        'is_invoices_view',
        'is_creditnotes_create',
        'is_creditnotes_edit',
        'is_creditnotes_delete',
        'is_creditnotes_view',
        'is_debitnotes_create',
        'is_debitnotes_edit',
        'is_debitnotes_delete',
        'is_debitnotes_view',
        'is_clientpayments_create',
        'is_clientpayments_edit',
        'is_clientpayments_delete',
        'is_clientpayments_view',
        'is_clientsoa_create',
        'is_clientsoa_edit',
        'is_clientsoa_delete',
        'is_clientsoa_view',
        'is_vendorexpenses_create',
        'is_vendorexpenses_edit',
        'is_vendorexpenses_delete',
        'is_vendorexpenses_view',
        'is_bills_create',
        'is_bills_edit',
        'is_bills_delete',
        'is_bills_view',
        'is_vendorpayments_create',
        'is_vendorpayments_edit',
        'is_vendorpayments_delete',
        'is_vendorpayments_view',
        'is_vendorsoa_create',
        'is_vendorsoa_edit',
        'is_vendorsoa_delete',
        'is_vendorsoa_view',
         //Procurment & Stock Tab
        'is_products_tab',
        'is_receiveorders_tab',
        'is_vendors_tab',
        'is_purchaseorders_tab',
        'is_transfers_tab',
        'is_productsdivision_tab',
        'is_productsaggregation_tab',
        'is_products_create',
        'is_products_edit',
        'is_products_delete',
        'is_products_view',
        'is_receiveorders_create',
        'is_receiveorders_edit',
        'is_receiveorders_delete',
        'is_receiveorders_view',
        'is_vendors_create',
        'is_vendors_edit',
        'is_vendors_delete',
        'is_vendors_view',
        'is_purchaseorders_create',
        'is_purchaseorders_edit',
        'is_purchaseorders_delete',
        'is_purchaseorders_view',
        'is_transfers_create',
        'is_transfers_edit',
        'is_transfers_delete',
        'is_transfers_view',
        'is_productsdivision_create',
        'is_productsdivision_edit',
        'is_productsdivision_delete',
        'is_productsdivision_view',
        'is_productsaggregation_create',
        'is_productsaggregation_edit',
        'is_productsaggregation_delete',
        'is_productsaggregation_view',
        'is_stockmovement_view',
        'is_stockmovement_tab',
        //overview
        'is_displayoverview_tab',
        'is_displaysales_tab',
        'is_displayaccounting_tab',
        'is_displaystock_tab',
        //production
        'is_production_tab',
        'is_displayproduction_tab',

        //shipments
        'is_shipping_tab',
        'is_Define_Shippers_tab',
        'is_Define_Shippers_create',
        'is_Define_Shippers_edit',
        'is_Define_Shippers_delete',
        'is_Define_Shippers_view',
                                    
        'is_Shipments_tab',
        'is_Shipments_create',
        'is_Shipments_edit',
        'is_Shipments_delete',
        'is_Shipments_view',
                                        
        'is_Receive_Shipments_tab',
        'is_Receive_Shipments_create',
        'is_Receive_Shipments_edit',
        'is_Receive_Shipments_delete',
        'is_Receive_Shipments_view',
                                        
        'is_Shippers_Bills_tab',
        'is_Shippers_Bills_create',
        'is_Shippers_Bills_edit',
        'is_Shippers_Bills_delete',
        'is_Shippers_Bills_view',
                                        
        'is_Shippers_Payments_tab',
        'is_Shippers_Payments_create',
        'is_Shippers_Payments_edit',
        'is_Shippers_Payments_delete',
        'is_Shippers_Payments_view',
                                        
        'is_Shippers_SOA_tab',
        'is_Shippers_SOA_create',
        'is_Shippers_SOA_edit',
        'is_Shippers_SOA_delete',
        'is_Shippers_SOA_view',

        'is_journalvoucher_tab',
        'is_trialbalance_tab',
        'is_journalvoucher_create',
        'is_journalvoucher_edit',
        'is_journalvoucher_delete',
        'is_journalvoucher_view',

    ];

    protected $fillable = [
        'name', 'title', 'telephone', 'extension', 'mobile_number',
        'email', 'password', 'email_signature',
        'is_admin',
        'is_active',
        'is_settings_tab',
        'is_sales_tab',
        'manager_id',
        'is_procurment_tab',
        'is_accounting_tab',
        'is_company_tab',
        'is_dashboard',
        //settings
        'is_deliverycondition_tab',
        'is_paymentcondition_tab',
        'is_exchangerate_tab',
        'is_uom_tab',
        'is_counters_tab',
        'is_currencies_tab',
        'is_warehouses_tab',
        'is_categories_tab',
        'is_subcategories_tab',
        'is_deliverycondition_create',
        'is_deliverycondition_edit',
        'is_deliverycondition_delete',
        'is_deliverycondition_view',
        'is_paymentcondition_create',
        'is_paymentcondition_edit',
        'is_paymentcondition_delete',
        'is_paymentcondition_view',
        'is_exchangerate_create',
        'is_exchangerate_edit',
        'is_exchangerate_delete',
        'is_exchangerate_view',
        'is_uom_create',
        'is_uom_edit',
        'is_uom_delete',
        'is_uom_view',
        'is_counters_create',
        'is_counters_edit',
        'is_counters_delete',
        'is_counters_view',
        'is_currencies_create',
        'is_currencies_edit',
        'is_currencies_delete',
        'is_currencies_view',
        'is_warehouses_create',
        'is_warehouses_edit',
        'is_warehouses_delete',
        'is_warehouses_view',
        'is_categories_create',
        'is_categories_edit',
        'is_categories_delete',
        'is_categories_view',
        'is_subcategories_create',
        'is_subcategories_edit',
        'is_subcategories_delete',
        'is_subcategories_view',
        //company
        'is_accounts_tab',
        'is_transferaccounts_tab',
        'is_deposit_tab',
        'is_returndeposit_tab',
        'is_employees_tab',
        'is_payroll_tab',
        'is_accounts_create',
        'is_accounts_edit',
        'is_accounts_delete',
        'is_accounts_view',
        'is_transferaccounts_create',
        'is_transferaccounts_edit',
        'is_transferaccounts_delete',
        'is_transferaccounts_view',
        'is_deposit_create',
        'is_deposit_edit',
        'is_deposit_delete',
        'is_deposit_view',
        'is_returndeposit_create',
        'is_returndeposit_edit',
        'is_returndeposit_delete',
        'is_returndeposit_view',
        'is_employees_create',
        'is_employees_edit',
        'is_employees_delete',
        'is_employees_view',
        'is_payroll_create',
        'is_payroll_edit',
        'is_payroll_delete',
        'is_payroll_view',
        //sales
        'is_clients_tab',
        'is_quotations_tab',
        'is_salesorders_tab',
        'is_clients_create',
        'is_clients_edit',
        'is_clients_delete',
        'is_clients_view',
        'is_quotations_create',
        'is_quotations_edit',
        'is_quotations_delete',
        'is_quotations_view',
        'is_salesorders_create',
        'is_salesorders_edit',
        'is_salesorders_delete',
        'is_salesorders_view',
        //Accounting Tab
        'is_advancepayments_tab',
        'is_invoices_tab',
        'is_creditnotes_tab',
        'is_debitnotes_tab',
        'is_clientpayments_tab',
        'is_clientsoa_tab',
        'is_vendorexpenses_tab',
        'is_bills_tab',
        'is_vendorpayments_tab',
        'is_vendorsoa_tab',
        'is_advancepayments_create',
        'is_advancepayments_edit',
        'is_advancepayments_delete',
        'is_advancepayments_view',
        'is_invoices_create',
        'is_invoices_edit',
        'is_invoices_delete',
        'is_invoices_view',
        'is_creditnotes_create',
        'is_creditnotes_edit',
        'is_creditnotes_delete',
        'is_creditnotes_view',
        'is_debitnotes_create',
        'is_debitnotes_edit',
        'is_debitnotes_delete',
        'is_debitnotes_view',
        'is_clientpayments_create',
        'is_clientpayments_edit',
        'is_clientpayments_delete',
        'is_clientpayments_view',
        'is_clientsoa_create',
        'is_clientsoa_edit',
        'is_clientsoa_delete',
        'is_clientsoa_view',
        'is_vendorexpenses_create',
        'is_vendorexpenses_edit',
        'is_vendorexpenses_delete',
        'is_vendorexpenses_view',
        'is_bills_create',
        'is_bills_edit',
        'is_bills_delete',
        'is_bills_view',
        'is_vendorpayments_create',
        'is_vendorpayments_edit',
        'is_vendorpayments_delete',
        'is_vendorpayments_view',
        'is_vendorsoa_create',
        'is_vendorsoa_edit',
        'is_vendorsoa_delete',
        'is_vendorsoa_view',
        //Procurment & Stock Tab
        'is_products_tab',
        'is_receiveorders_tab',
        'is_vendors_tab',
        'is_purchaseorders_tab',
        'is_transfers_tab',
        'is_productsdivision_tab',
        'is_productsaggregation_tab',
        'is_products_create',
        'is_products_edit',
        'is_products_delete',
        'is_products_view',
        'is_receiveorders_create',
        'is_receiveorders_edit',
        'is_receiveorders_delete',
        'is_receiveorders_view',
        'is_vendors_create',
        'is_vendors_edit',
        'is_vendors_delete',
        'is_vendors_view',
        'is_purchaseorders_create',
        'is_purchaseorders_edit',
        'is_purchaseorders_delete',
        'is_purchaseorders_view',
        'is_transfers_create',
        'is_transfers_edit',
        'is_transfers_delete',
        'is_transfers_view',
        'is_productsdivision_create',
        'is_productsdivision_edit',
        'is_productsdivision_delete',
        'is_productsdivision_view',
        'is_productsaggregation_create',
        'is_productsaggregation_edit',
        'is_productsaggregation_delete',
        'is_productsaggregation_view',
        'is_stockmovement_tab',
        'is_stockmovement_view',
         //overview
        'is_displayoverview_tab',
        'is_displaysales_tab',
        'is_displayaccounting_tab',
        'is_displaystock_tab',
        //production
        'is_production_tab',
        'is_displayproduction_tab',

        //shipments
        'is_shipping_tab',
        'is_Define_Shippers_tab',
        'is_Define_Shippers_create',
        'is_Define_Shippers_edit',
        'is_Define_Shippers_delete',
        'is_Define_Shippers_view',
                                    
        'is_Shipments_tab',
        'is_Shipments_create',
        'is_Shipments_edit',
        'is_Shipments_delete',
        'is_Shipments_view',
                                        
        'is_Receive_Shipments_tab',
        'is_Receive_Shipments_create',
        'is_Receive_Shipments_edit',
        'is_Receive_Shipments_delete',
        'is_Receive_Shipments_view',
                                        
        'is_Shippers_Bills_tab',
        'is_Shippers_Bills_create',
        'is_Shippers_Bills_edit',
        'is_Shippers_Bills_delete',
        'is_Shippers_Bills_view',
                                        
        'is_Shippers_Payments_tab',
        'is_Shippers_Payments_create',
        'is_Shippers_Payments_edit',
        'is_Shippers_Payments_delete',
        'is_Shippers_Payments_view',
                                        
        'is_Shippers_SOA_tab',
        'is_Shippers_SOA_create',
        'is_Shippers_SOA_edit',
        'is_Shippers_SOA_delete',
        'is_Shippers_SOA_view',

        
        'is_journalvoucher_tab',
        'is_trialbalance_tab',
        'is_journalvoucher_create',
        'is_journalvoucher_edit',
        'is_journalvoucher_delete',
        'is_journalvoucher_view',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
    
    protected $casts = [
        'is_admin'=> 'integer',
        'is_active'=> 'integer',
        'is_settings_tab'=> 'integer',
        'is_sales_tab'=> 'integer',
        'is_procurment_tab'=> 'integer',
        'is_accounting_tab'=> 'integer',
        'is_company_tab'=> 'integer',
        'is_dashboard'=> 'integer',
        //settings
        'is_deliverycondition_tab'=> 'integer',
        'is_paymentcondition_tab'=> 'integer',
        'is_exchangerate_tab'=> 'integer',
        'is_uom_tab'=> 'integer',
        'is_counters_tab'=> 'integer',
        'is_currencies_tab'=> 'integer',
        'is_warehouses_tab'=> 'integer',
        'is_categories_tab'=> 'integer',
        'is_subcategories_tab'=> 'integer',
        'is_deliverycondition_create'=> 'integer',
        'is_deliverycondition_edit'=> 'integer',
        'is_deliverycondition_delete'=> 'integer',
        'is_deliverycondition_view'=> 'integer',
        'is_paymentcondition_create'=> 'integer',
        'is_paymentcondition_edit'=> 'integer',
        'is_paymentcondition_delete'=> 'integer',
        'is_paymentcondition_view'=> 'integer',
        'is_exchangerate_create'=> 'integer',
        'is_exchangerate_edit'=> 'integer',
        'is_exchangerate_delete'=> 'integer',
        'is_exchangerate_view'=> 'integer',
        'is_uom_create'=> 'integer',
        'is_uom_edit'=> 'integer',
        'is_uom_delete'=> 'integer',
        'is_uom_view'=> 'integer',
        'is_counters_create'=> 'integer',
        'is_counters_edit'=> 'integer',
        'is_counters_delete'=> 'integer',
        'is_counters_view'=> 'integer',
        'is_currencies_create'=> 'integer',
        'is_currencies_edit'=> 'integer',
        'is_currencies_delete'=> 'integer',
        'is_currencies_view'=> 'integer',
        'is_warehouses_create'=> 'integer',
        'is_warehouses_edit'=> 'integer',
        'is_warehouses_delete'=> 'integer',
        'is_warehouses_view'=> 'integer',
        'is_categories_create'=> 'integer',
        'is_categories_edit'=> 'integer',
        'is_categories_delete'=> 'integer',
        'is_categories_view'=> 'integer',
        'is_subcategories_create'=> 'integer',
        'is_subcategories_edit'=> 'integer',
        'is_subcategories_delete'=> 'integer',
        'is_subcategories_view'=> 'integer',
        //company
        'is_accounts_tab'=> 'integer',
        'is_transferaccounts_tab'=> 'integer',
        'is_deposit_tab'=> 'integer',
        'is_returndeposit_tab'=> 'integer',
        'is_employees_tab'=> 'integer',
        'is_payroll_tab'=> 'integer',
        'is_accounts_create'=> 'integer',
        'is_accounts_edit'=> 'integer',
        'is_accounts_delete'=> 'integer',
        'is_accounts_view'=> 'integer',
        'is_transferaccounts_create'=> 'integer',
        'is_transferaccounts_edit'=> 'integer',
        'is_transferaccounts_delete'=> 'integer',
        'is_transferaccounts_view'=> 'integer',
        'is_deposit_create'=> 'integer',
        'is_deposit_edit'=> 'integer',
        'is_deposit_delete'=> 'integer',
        'is_deposit_view'=> 'integer',
        'is_returndeposit_create'=> 'integer',
        'is_returndeposit_edit'=> 'integer',
        'is_returndeposit_delete'=> 'integer',
        'is_returndeposit_view'=> 'integer',
        'is_employees_create'=> 'integer',
        'is_employees_edit'=> 'integer',
        'is_employees_delete'=> 'integer',
        'is_employees_view'=> 'integer',
        'is_payroll_create'=> 'integer',
        'is_payroll_edit'=> 'integer',
        'is_payroll_delete'=> 'integer',
        'is_payroll_view'=> 'integer',
        //sales
        'is_clients_tab'=> 'integer',
        'is_quotations_tab'=> 'integer',
        'is_salesorders_tab'=> 'integer',
        'is_clients_create'=> 'integer',
        'is_clients_edit'=> 'integer',
        'is_clients_delete'=> 'integer',
        'is_clients_view'=> 'integer',
        'is_quotations_create'=> 'integer',
        'is_quotations_edit'=> 'integer',
        'is_quotations_delete'=> 'integer',
        'is_quotations_view'=> 'integer',
        'is_salesorders_create'=> 'integer',
        'is_salesorders_edit'=> 'integer',
        'is_salesorders_delete'=> 'integer',
        'is_salesorders_view'=> 'integer',
         //Accounting Tab
        'is_advancepayments_tab'=> 'integer',
        'is_invoices_tab'=> 'integer',
        'is_creditnotes_tab'=> 'integer',
        'is_debitnotes_tab'=> 'integer',
        'is_clientpayments_tab'=> 'integer',
        'is_clientsoa_tab'=> 'integer',
        'is_vendorexpenses_tab'=> 'integer',
        'is_bills_tab'=> 'integer',
        'is_vendorpayments_tab'=> 'integer',
        'is_vendorsoa_tab'=> 'integer',
        'is_advancepayments_create'=> 'integer',
        'is_advancepayments_edit'=> 'integer',
        'is_advancepayments_delete'=> 'integer',
        'is_advancepayments_view'=> 'integer',
        'is_invoices_create'=> 'integer',
        'is_invoices_edit'=> 'integer',
        'is_invoices_delete'=> 'integer',
        'is_invoices_view'=> 'integer',
        'is_creditnotes_create'=> 'integer',
        'is_creditnotes_edit'=> 'integer',
        'is_creditnotes_delete'=> 'integer',
        'is_creditnotes_view'=> 'integer',
        'is_debitnotes_create'=> 'integer',
        'is_debitnotes_edit'=> 'integer',
        'is_debitnotes_delete'=> 'integer',
        'is_debitnotes_view'=> 'integer',
        'is_clientpayments_create'=> 'integer',
        'is_clientpayments_edit'=> 'integer',
        'is_clientpayments_delete'=> 'integer',
        'is_clientpayments_view'=> 'integer',
        'is_clientsoa_create'=> 'integer',
        'is_clientsoa_edit'=> 'integer',
        'is_clientsoa_delete'=> 'integer',
        'is_clientsoa_view'=> 'integer',
        'is_vendorexpenses_create'=> 'integer',
        'is_vendorexpenses_edit'=> 'integer',
        'is_vendorexpenses_delete'=> 'integer',
        'is_vendorexpenses_view'=> 'integer',
        'is_bills_create'=> 'integer',
        'is_bills_edit'=> 'integer',
        'is_bills_delete'=> 'integer',
        'is_bills_view'=> 'integer',
        'is_vendorpayments_create'=> 'integer',
        'is_vendorpayments_edit'=> 'integer',
        'is_vendorpayments_delete'=> 'integer',
        'is_vendorpayments_view'=> 'integer',
        'is_vendorsoa_create'=> 'integer',
        'is_vendorsoa_edit'=> 'integer',
        'is_vendorsoa_delete'=> 'integer',
        'is_vendorsoa_view'=> 'integer',
        //Procurment & Stock Tab
        'is_products_tab'=> 'integer',
        'is_receiveorders_tab'=> 'integer',
        'is_vendors_tab'=> 'integer',
        'is_purchaseorders_tab'=> 'integer',
        'is_transfers_tab'=> 'integer',
        'is_productsdivision_tab'=> 'integer',
        'is_productsaggregation_tab'=> 'integer',
        'is_products_create'=> 'integer',
        'is_products_edit'=> 'integer',
        'is_products_delete'=> 'integer',
        'is_products_view'=> 'integer',
        'is_receiveorders_create'=> 'integer',
        'is_receiveorders_edit'=> 'integer',
        'is_receiveorders_delete'=> 'integer',
        'is_receiveorders_view'=> 'integer',
        'is_vendors_create'=> 'integer',
        'is_vendors_edit'=> 'integer',
        'is_vendors_delete'=> 'integer',
        'is_vendors_view'=> 'integer',
        'is_purchaseorders_create'=> 'integer',
        'is_purchaseorders_edit'=> 'integer',
        'is_purchaseorders_delete'=> 'integer',
        'is_purchaseorders_view'=> 'integer',
        'is_transfers_create'=> 'integer',
        'is_transfers_edit'=> 'integer',
        'is_transfers_delete'=> 'integer',
        'is_transfers_view'=> 'integer',
        'is_productsdivision_create'=> 'integer',
        'is_productsdivision_edit'=> 'integer',
        'is_productsdivision_delete'=> 'integer',
        'is_productsdivision_view'=> 'integer',
        'is_productsaggregation_create'=> 'integer',
        'is_productsaggregation_edit'=> 'integer',
        'is_productsaggregation_delete'=> 'integer',
        'is_productsaggregation_view'=> 'integer',
        'is_stockmovement_tab'=> 'integer',
        'is_stockmovement_view'=> 'integer',
         //overview
        'is_displayoverview_tab'=> 'integer',
        'is_displaysales_tab'=> 'integer',
        'is_displayaccounting_tab'=> 'integer',
        'is_displaystock_tab'=> 'integer',
        //production
        'is_production_tab'=> 'integer',
        'is_displayproduction_tab'=> 'integer',

        //shipments
        'is_shipping_tab'=> 'integer',
        'is_Define_Shippers_tab'=> 'integer',
        'is_Define_Shippers_create'=> 'integer',
        'is_Define_Shippers_edit'=> 'integer',
        'is_Define_Shippers_delete'=> 'integer',
        'is_Define_Shippers_view'=> 'integer',
                                    
        'is_Shipments_tab'=> 'integer',
        'is_Shipments_create'=> 'integer',
        'is_Shipments_edit'=> 'integer',
        'is_Shipments_delete'=> 'integer',
        'is_Shipments_view'=> 'integer',
                                        
        'is_Receive_Shipments_tab'=> 'integer',
        'is_Receive_Shipments_create'=> 'integer',
        'is_Receive_Shipments_edit'=> 'integer',
        'is_Receive_Shipments_delete'=> 'integer',
        'is_Receive_Shipments_view'=> 'integer',
                                        
        'is_Shippers_Bills_tab'=> 'integer',
        'is_Shippers_Bills_create'=> 'integer',
        'is_Shippers_Bills_edit'=> 'integer',
        'is_Shippers_Bills_delete'=> 'integer',
        'is_Shippers_Bills_view'=> 'integer',
                                        
        'is_Shippers_Payments_tab'=> 'integer',
        'is_Shippers_Payments_create'=> 'integer',
        'is_Shippers_Payments_edit'=> 'integer',
        'is_Shippers_Payments_delete'=> 'integer',
        'is_Shippers_Payments_view'=> 'integer',
                                        
        'is_Shippers_SOA_tab'=> 'integer',
        'is_Shippers_SOA_create'=> 'integer',
        'is_Shippers_SOA_edit'=> 'integer',
        'is_Shippers_SOA_delete'=> 'integer',
        'is_Shippers_SOA_view'=> 'integer',

        'is_journalvoucher_tab'=> 'integer',
        'is_trialbalance_tab'=> 'integer',
        'is_journalvoucher_create'=> 'integer',
        'is_journalvoucher_edit'=> 'integer',
        'is_journalvoucher_delete'=> 'integer',
        'is_journalvoucher_view'=> 'integer',
    ];

    protected $appends = ['text'];

    
    public function manager()
    {
        return $this->belongsTo(User::class,'manager_id','id');
    }

    public function getTextAttribute()
    {
        return $this->attributes['name'];
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}
